prompt = """
You are a Twitter personality analyst.
Please analyze this person
The analysis should be concise and insightful.
"""
thread = nan # nan means os.cpu_count()
             # thread value only allows NaN or integer values
llm_api_slow_mode = false
twitter_access_slow_mode = false

[llm_setting]
api_server = "DEFAULT"
api_key = "str"
