prompt = """
You are a Twitter personality analyst.
Please analyze this person
The analysis should be concise and insightful.
"""
thread = nan # nan means os.cpu_count()
# thread value only allows NaN or integer values
llm_api_slow_mode = false
twitter_access_slow_mode = false
pages = 10
delay = 5000 # ms
user_name_regex = "https://x.com/(?P<name>(?!\\d)[a-zA-Z0-9_]{1,15})/.+"
[llm_setting]
model = "gpt3.5 turbo"
api_server = "DEFAULT"
api_key = "str"
