birthday_var = "window.__INITIAL_STATE__"

[profile_json]
expr = "//script[@data-testid='UserProfileSchema-test']"

  [profile_json.jq]
  nickname = ".author.givenName"
  bio = ".author.description"
  location = ".author.homeLocation.name"
  followed = '.author.interactionStatistic[] | select(.name == "Follows").userInteractionCount'
  follower = '.author.interactionStatistic[] | select(.name == "Friends").userInteractionCount'
  tweet_count = '.author.interactionStatistic[] | select(.name == "Tweets").userInteractionCount'
  join_time = '.dateCreated'
[tweet]
link = "//time/parent::a"
media = '//*[@data-testid="tweetText"]/ancestor::*[3]//img | //*[@data-testid="tweetText"]/ancestor::*[3]//video'
text = '//*[@data-testid="tweetText"]'
time = "//time/@datetime"
