[profile_json]
expr = "//script[@data-testid='UserProfileSchema-test']"

[profile_json.jq]
nickname = ".author.givenName"
bio = ".author.description"
location = ".author.homeLocation.name"
followed = '.author.interactionStatistic[] | select(.name == "Follows").userInteractionCount'
follower = '.author.interactionStatistic[] | select(.name == "Friends").userInteractionCount'
tweet_count = '.author.interactionStatistic[] | select(.name == "Tweets").userInteractionCount'
join_time = '.dateCreated'
[tweet]
link = "//time/parent::a"
media = '//div[@data-testid="tweetPhoto"] | //div[@data-testid="videoComponent"]'
text =  '//*[@data-testid="tweetText"]'
time = "//time/@datetime"
frame = '(//div[@data-testid="cellInnerDiv"])[1]'
sensitive_content = "//div/div/div/div/div[2]/div/button"
[TMD]
button = '//div[contains(@class, "tmd-down")]'
click = """
let element = document.querySelector('div.tmd-down');
element.addEventListener('click', () => hasClickEvent = true);
element.dispatchEvent(new Event('click'));
""" # Avoid being unable to download images of private posts
