[profile_json]
expr = "//script[@data-testid='UserProfileSchema-test']"

[profile_json.jq]
nickname = ".author.givenName"
bio = ".author.description"
location = ".author.homeLocation.name"
followed = '.author.interactionStatistic[] | select(.name == "Follows").userInteractionCount'
follower = '.author.interactionStatistic[] | select(.name == "Friends").userInteractionCount'
tweet_count = '.author.interactionStatistic[] | select(.name == "Tweets").userInteractionCount'
join_time = '.dateCreated'
[tweet]
link = "//time/parent::a"
media = "xpath=/html/body/div[1]/div/div/div[2]/main/div/div/div/div/div/section/div/div/div[1]/div/div/article/div/div/div[3]/div[2]" #'//*[@data-testid="tweetText"]/ancestor::*[3]//img | //*[@data-testid="tweetText"]/ancestor::*[3]//video'
text =  "xpath=/html/body/div[1]/div/div/div[2]/main/div/div/div/div/div/section/div/div/div[1]/div/div/article/div/div/div[3]/div[1]/div/div"#'//*[@data-testid="tweetText"]'
time = "//time/@datetime"
